name: 更新 WakaTime Stats

# 手动触发或每天凌晨 0 点自动跑一次
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 生成并提交 WakaTime 统计
        uses: claserre9/wakatime-stats@v1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_USER_ID: ${{ secrets.WAKATIME_USER_ID }}
          GH_TOKEN:         ${{ secrets.GH_TOKEN }}
